"$schema" = 'https://starship.rs/config-schema.json'

format = """
[î‚¶](#fa824c)\
$directory\
[î‚´](fg:#fa824c bg:#716969)\
$git_branch\
$git_status\
[î‚´](fg:#716969 bg:#2d2e2e)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$bun\
$python\
$nim\
$rust\
$scala\
$nix_shell\
[î‚´](fg:#2d2e2e bg:#0f0f0f)\
$docker_context\
[î‚´ ](fg:#0f0f0f)\
\n$character"""

add_newline = true

[character]
success_symbol = "[â¯](fg:#fa824c)"
# error_symbol = "[ï”°](fg:#fa824c)"

# You can also replace your username with a neat symbol like ï„   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#716969"
style_root = "bg:#716969"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[directory]
style = "bg:#fa824c"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"repos" = "îœ‰ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#0f0f0f"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = "î‰µ "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#716969"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#716969"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#2d2e2e"
format = '[ $symbol ]($style)'

[bun]
style = "bg:#2d2e2e"
symbol = "ğŸš€ "
format = '[ $symbol($version) ]($style)'

[python]
style = "bg:#2d2e2e"
format = '[ $symbol($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#2d2e2e"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = "ó±„…"
style = "bg:#2d2e2e"
format = '[$symbol $name ]($style)'

[time]
disabled = false
time_format = "%R"              # Hour:Minute Format
style = "bg:#fbfbfb fg:#2d2e2e"
format = '[ $time ]($style)'
